# Generated by Django 6.0.1 on 2026-01-25 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_tarefa_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
